### ISSUE TITLE
Translation EN -> JP

### ISSUE THREAD

**Issue by Riunia** [bodinaren/maplestory-skills#22]
Hi!

I found this repository through ArrowVulcan's Skill Calculator repository. I was wondering if it would be possible to translate this page for Japanese users to use (with some minor adjustments)? I will of course credit you for originally creating the repository to use.

The minor adjustments I would be making are:
- Translation of the text.
- Disabling classes not yet released (we do not have Runeblade, Soul Binder or Striker yet) as well as Awakening skills (we also do not have Awakening yet). I would like to hide them from view until they are released.
- Adjusting remaining skill points to be 68 (ie: pre-awakening amount).

If you reject this request, I understand completely. Thank you again for taking the time to read this.

**Comment by bodinaren** [comment]
Hi,

Of course, I'd be happy if this was available in more languages and servers! I wonder if it'd be possible (with reasonable effort) to support Japanese within the same package rather than making a new fork. I'll think on that. Either way though, feel free to fork and get started! If I can figure out a good way I might merge it back, if you don't mind?

If you need any guidance, feel free to ask in this issue.

Good luck 👍
